name = "naver-cafe-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
SUPABASE_URL = "https://cbcftfkiosikuofmvwus.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiY2Z0Zmtpb3Npa3VvZm12d3VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDI3NTgsImV4cCI6MjA2ODgxODc1OH0.ol5b8z9JRZBKLpAjaNGDMzxVbFbBV0pzd9AKsoYlxw4"